config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  resources :publications
  resources :people
  resources :faculties
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# This class is the parent class of all entities from database.
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faculty.rb
# frozen_string_literal: true

# This class represents a faculty.
class Faculty < ApplicationRecord
  has_many :people, dependent: :destroy

  validates :name, presence: true
  validates :code, presence: true
end

app/models/person.rb
# frozen_string_literal: true

# This class represents a person.
class Person < ApplicationRecord
  belongs_to :faculty
  has_many :publications, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :username, presence: true
  validate :email_valid

  def email_valid
    errors.add(:email, :error) unless /.+@.+(\.[^.]+)+/.match?(email)
  end

  def publications
    Publication.where(person_id: id)
  end
end

app/models/publication.rb
# frozen_string_literal: true

# This class represents a publication.
class Publication < ApplicationRecord
  belongs_to :person

  validates :title, presence: true

  def faculty
    person = Person.find(person_id)
    faculty_id = person.faculty_id
    Faculty.find(faculty_id)
  end

  def published?
    published <= Date.today
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Thic class is the base of all the controllers in the application.
class ApplicationController < ActionController::Base
end

app/controllers/faculties_controller.rb
# frozen_string_literal: true

# This class is a controller for managing faculties.
class FacultiesController < ApplicationController
  before_action :set_faculty, only: %i[show edit update destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show; end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit; end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)
    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_faculty
    @faculty = Faculty.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def faculty_params
    params.require(:faculty).permit(:name, :code, :note)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# This class is the home controller.
class HomeController < ApplicationController
  def index; end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

# This class is a controller for managing people.
class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show; end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit; end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def person_params
    params.require(:person).permit(:name, :email, :username, :faculty_id)
  end
end

app/controllers/publications_controller.rb
# frozen_string_literal: true

# This class is a controller for managing publicatoins.
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[show edit update destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show; end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit; end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_publication
    @publication = Publication.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def publication_params
    params.require(:publication).permit(:title, :published, :abstract, :person_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# This class is the base helper for the whole application.
module ApplicationHelper
end

app/helpers/faculties_helper.rb
# frozen_string_literal: true

# This class is the base helper for working with faculties.
module FacultiesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/people_helper.rb
# frozen_string_literal: true

# This class is the base helper for working with people.
module PeopleHelper
end

app/helpers/publications_helper.rb
# frozen_string_literal: true

# This class is the base helper for working with publications.
module PublicationsHelper
end

app/views/faculties/_form.html.erb
<%= form_for @faculty, :html => { :class => "form-horizontal faculty" } do |f| %>

  <% if @faculty.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@faculty.errors.count, "error") %> prohibited this faculty from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @faculty.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :name, :style => 'margin-left: 1.5em' %>
    <%= f.text_field :name, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)' %>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :code, :style => 'margin-left: 1.5em'  %>
    <%= f.text_field :code, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)' %>
    <%=f.error_span(:code) %>
  </div>
  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :note, :style => 'margin-left: 1.5em'  %>
    <%= f.text_area :note, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)' %>
    <%=f.error_span(:note) %>
  </div>

  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <div class="ml-auto text-right" style="margin-right: 1.5em;">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                faculties_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/faculties/edit.html.erb
<%- model_class = Faculty -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/faculties/index.html.erb
<%- model_class = Faculty -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:note) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= link_to faculty.id, faculty_path(faculty) %></td>
        <td><%= faculty.name %></td>
        <td><%= faculty.code %></td>
        <td><%= faculty.note %></td>
        <td><%=l faculty.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_faculty_path(faculty), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      faculty_path(faculty),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger',
                      :style => 'color: white' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="5"></td>
      <td><%= link_to t('.new', :default => t("helpers.links.new")),
        new_faculty_path,
        :class => 'btn btn-primary',
        :style => 'color: white' %></td>
    </tr>
  </tfoot>
</table>

app/views/faculties/new.html.erb
<%- model_class = Faculty -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/faculties/show.html.erb
<%- model_class = Faculty -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @faculty.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @faculty.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @faculty.note %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              faculties_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_faculty_path(@faculty), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              faculty_path(@faculty),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger',
              :style => 'color: white' %>

app/views/home/index.html.erb
<h1>Home</h1>
<p>Find me in app/views/home/index.html.erb</p>
<ul>
    <li><%= link_to 'Faculties', faculties_path %></li>
    <li><%= link_to 'People', people_path %></li>
    <li><%= link_to 'Publications', publications_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework07</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => "form-horizontal person" } do |f| %>

  <% if @person.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :name, :style => 'margin-left: 1.5em' %>
    <%= f.text_field :name, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)' %>
    <%= f.error_span(:name) %>
  </div>
  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :email, :style => 'margin-left: 1.5em' %>
    <%= f.email_field :email, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)' %>
    <%= f.error_span(:email)  %>
  </div>
  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :username, :style => 'margin-left: 1.5em' %>
    <%= f.text_field :username, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)' %>
    <%= f.error_span(:username) %>
  </div>
  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :faculty_id, :style => 'margin-left: 1.5em' %>
    <%= f.text_field :faculty_id, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)' %>
    <%= f.error_span(:faculty_id) %>
  </div>

  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <div class="ml-auto text-right" style="margin-right: 1.5em;">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:faculty_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= person.username %></td>
        <td><%= person.faculty_id %></td>
        <td><%=l person.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger',
                      :style => 'color: white' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="6"></td>
      <td><%= link_to t('.new', :default => t("helpers.links.new")),
        new_person_path,
        :class => 'btn btn-primary',
        :style => 'color: white' %></td>
    </tr>
  </tfoot>
</table>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @person.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @person.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:faculty_id) %>:</strong></dt>
  <dd><%= @person.faculty_id %></dd>
  <dt><strong><%= I18n.t('publications') %>:</strong></dt>
  <dd>
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= model_class.human_attribute_name(:id) %></th>
            <th><%= model_class.human_attribute_name(:title) %></th>
            <th><%= model_class.human_attribute_name(:published) %></th>
            <th><%= model_class.human_attribute_name(:abstract) %></th>
          </tr>
        </thead>
        <tbody>
          <% @person.publications.each do |publication| %>
            <tr>
              <td><%= link_to publication.id, publication_path(publication) %></td>
              <td><%= publication.title %></td>
              <td><%= publication.published? %></td>
              <td><%= publication.abstract %></td>
                
            </tr>
          <% end %>
        </tbody>
      </table>
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger',
              :style => 'color: white' %>

app/views/publications/_form.html.erb
<%= form_for @publication, :html => { :class => "form-horizontal publication" } do |f| %>

  <% if @publication.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @publication.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :title, :style => 'margin-left: 1.5em; width: calc(100% - 3em)'  %>
    <%= f.text_field :title, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)'%>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :published, :style => 'margin-left: 1.5em; width: calc(100% - 3em)' %>
    <%= f.date_field :published, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)' %>
    <%=f.error_span(:published) %>
  </div>
  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :abstract, :style => 'margin-left: 1.5em; width: calc(100% - 3em)'  %>
    <%= f.text_area :abstract, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)'%>
    <%=f.error_span(:abstract) %>
  </div>
  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <%= f.label :person_id, :style => 'margin-left: 1.5em; width: calc(100% - 3em)' %>
    <%= f.text_field :person_id, :class => 'form-control', :style => 'margin-left: 1.5em; width: calc(100% - 3em)'%>
    <%=f.error_span(:person_id) %>
  </div>

  <div class="form-group" style="margin-left: 0; margin-right: 0;">
    <div class="ml-auto text-right" style="margin-right: 1.5em;">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                publications_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/publications/edit.html.erb
<%- model_class = Publication -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/publications/index.html.erb
<%- model_class = Publication -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:published) %></th>
      <th><%= model_class.human_attribute_name(:published) %></th>
      <th><%= model_class.human_attribute_name(:abstract) %></th>
      <th><%= model_class.human_attribute_name(:person_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= link_to publication.id, publication_path(publication) %></td>
        <td><%= publication.title %></td>
        <td><%= publication.published %></td>
        <td><%= publication.published? %></td>
        <td><%= publication.abstract %></td>
        <td><%= publication.person_id %></td>
        <td><%=l publication.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_publication_path(publication), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      publication_path(publication),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger',
                      :style => 'color: white' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="7"></td>
      <td><%= link_to t('.new', :default => t("helpers.links.new")),
                    new_publication_path,
                    :class => 'btn btn-primary',
                    :style => 'color: white' %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/publications/new.html.erb
<%- model_class = Publication -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/publications/show.html.erb
<%- model_class = Publication -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @publication.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:published) %>:</strong></dt>
  <dd><%= @publication.published %></dd>
  <dt><strong><%= model_class.human_attribute_name(:abstract) %>:</strong></dt>
  <dd><%= @publication.abstract %></dd>
  <dt><strong><%= model_class.human_attribute_name(:person_id) %>:</strong></dt>
  <dd><%= @publication.person_id %></dd>
  <dt><strong><%= I18n.t('faculty') %>:</strong></dt>
  <dd><%= @publication.faculty.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              publications_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_publication_path(@publication), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              publication_path(@publication),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger',
              :style => 'color: white' %>